baseURL = "/"
languageCode = "en-us"
defaultContentLanguage = "fr"
theme = "relearn"
pygmentsUseClasses = true
relativeURLs = true

[params]
  themeVariant = "mine"
  showVisitedLinks = true
  disableInlineCopyToClipBoard = true
  disableLandingPageButton = true
  disableLanguageSwitchingButton = true
  disableSearch = true
  custom_css = ["css/syntax.css"]
  finalURL = "https://igm.univ-mlv.fr/~marsault/cpp/cours/"
  cpprefURL = "https://igm.univ-mlv.fr/~marsault/cpp/ref/en/"
  tpURL = "https://github.com/marsault/CPP_Exercises/"
  exoducoursURL = "https://github.com/marsault/CPP_Learning_Code/"
  formsubmitco_token = "08af4b8e13fc3ec785faa99820631150"
  titleSeparator = ' '
  reverse = true

  
[markup]
  [markup.highlight]
    guessSyntax = false 
  [markup.goldmark.renderer]
    unsafe = true

[Languages]
[Languages.fr]
title = "C++::"
weight = 1
languageName = "Français"


[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Dépôt git des sujets de TPs"
url = "https://github.com/marsault/CPP_Exercises/"
weight = 2

[[menu.shortcuts]]
name = "<i class='far fa-file-powerpoint'></i> Slides"
url = "/slides"
weight = 3

#[[menu.shortcuts]]
#name = "<i class='far fa-list-alt'></i> Workflow"
#url = "/workflow"
#weight = 4

#[[menu.shortcuts]]
#name = "<i class='fas fa-question-circle'></i> FAQ"
#url = "/faq"
#weight = 5

[[menu.shortcuts]]
name = "<i class='fa fa-rocket'></i> Astuces"
url = "/chapter0/6-tips/"
weight = 6

[[menu.shortcuts]]
name = "<i class='fas fa-cog'></i> Compiler Explorer"
url = "https://godbolt.org/"
weight = 7

[[menu.shortcuts]]
name = "<i class='fas fa-passport'></i> (Copie locale de) CPP-Ref"
url = "https://www-igm.univ-mlv.fr/~marsault/cpp/ref/en/"
weight = 8
